# Default values for container1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# QoS Guaranteed for memory, Burstable for cpu

image:
  repository: lejeunen/container1

resources:
  requests:
    memory: "512M"
    cpu: "0.1"
  limits:
    memory: "512M"


env:
- name: JVM_OPTS
  value: "-Xmx300M"
